<a href="https://colab.research.google.com/github/chenpetro/04_08_22_Lesson8_Semester2_Web_1_01_2/blob/main/2026_02_04_Python_Petro_Chen_numpy_slicing_diagonal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

# now we show how to do slicing.  the general format for a 2x2 array is

# a[from : to -1 , from : to -1]

# the colon by itself means all elements, like a[:,:]

# so the comma seperates the axis and the colon says what to do within the axis


# first columns from the 4th and 5th rows
# remember we start counting array elements at 0 so we write 3 when we mean element 4

arr=np.random.randint(1,100,(10,10))

arr


array([[99, 70, 67, 64, 26, 86, 73, 97, 63, 45],
       [64, 79, 97, 68, 70, 64,  3, 55, 98, 93],
       [ 2, 93, 80, 70, 65, 40, 14, 11, 64, 29],
       [64, 67, 35, 24, 94, 36, 31, 88,  8, 91],
       [76, 20,  5, 15, 74, 10, 71, 27, 49, 36],
       [99, 53, 12, 88, 41, 94, 97, 62, 28, 54],
       [51, 68,  1, 23, 91, 82, 50, 33, 67, 78],
       [36, 45, 98, 67, 58, 82, 75,  2, 12,  2],
       [92,  3, 89,  5, 70, 28, 55, 65, 72, 98],
       [99, 51, 54, 97, 54, 77, 64, 63, 34, 57]])

In [ ]:
arr[3:5,:]

array([[64, 67, 35, 24, 94, 36, 31, 88,  8, 91],
       [76, 20,  5, 15, 74, 10, 71, 27, 49, 36]])

In [ ]:
# arr[rows, columns]

# arrr[start:stop -1, start-stop - 1]

arr[3:5,0:2]

array([[64, 67],
       [76, 20]])

In [ ]:
arr=np.random.randint(1,100,(2,5,10))

In [ ]:
arr

array([[[83, 63, 76, 76, 38, 69, 92, 81, 32, 89],
        [52, 92, 38,  9, 47, 87, 92, 30, 44, 77],
        [95,  3, 55, 95, 26, 24, 49, 99, 14, 26],
        [57,  2, 39, 11, 51, 93, 66, 21, 24, 75],
        [91, 12, 73,  2,  2, 80, 59,  9, 32, 21]],

       [[ 3,  7, 96, 28, 96, 46, 69, 50, 29, 89],
        [77,  2, 17, 31, 89, 58, 77, 19, 75, 65],
        [31, 45, 58, 61, 86, 89, 75, 81, 68, 13],
        [79,  5, 64, 64, 18, 40, 25, 34, 58, 74],
        [37, 74, 20, 88, 22, 47, 94, 40, 58, 63]]])

In [ ]:
# get the first two dimensional array

arr[0,:,:]

array([[83, 63, 76, 76, 38, 69, 92, 81, 32, 89],
       [52, 92, 38,  9, 47, 87, 92, 30, 44, 77],
       [95,  3, 55, 95, 26, 24, 49, 99, 14, 26],
       [57,  2, 39, 11, 51, 93, 66, 21, 24, 75],
       [91, 12, 73,  2,  2, 80, 59,  9, 32, 21]])

In [ ]:
# get first two rows out of first 2 dimensional array in this 3 dimensional object

b=arr[0,0:2,:]
b

array([[83, 63, 76, 76, 38, 69, 92, 81, 32, 89],
       [52, 92, 38,  9, 47, 87, 92, 30, 44, 77]])

In [ ]:
b.shape

(2, 10)

In [ ]:
b.reshape(1,20)

array([[83, 63, 76, 76, 38, 69, 92, 81, 32, 89, 52, 92, 38,  9, 47, 87,
        92, 30, 44, 77]])

In [ ]:
b.reshape(1,-1)

array([[83, 63, 76, 76, 38, 69, 92, 81, 32, 89, 52, 92, 38,  9, 47, 87,
        92, 30, 44, 77]])

In [ ]:
b.reshape(5,-1)

array([[83, 63, 76, 76],
       [38, 69, 92, 81],
       [32, 89, 52, 92],
       [38,  9, 47, 87],
       [92, 30, 44, 77]])

In [ ]:
arr=np.random.randint(1,100,(4,4))

arr

array([[74, 20, 35, 44],
       [77, 93, 67, 69],
       [14, 73, 25, 46],
       [11, 25, 97, 81]])

In [ ]:
arr[2,2]

np.int64(25)

In [ ]:
arr[1,1]

np.int64(93)

In [ ]:
#hard code diagonal

# diagonal are elements such that row_number = col_number



[a[0,0],a[1,1],a[2,2],a[3,3]]

# Homework

1. (difficult) create a  4 x 4 array, how can you print elements along the diagonal.  write a for-loop

2.  easy.  create an array of numbers from 1 to 25 with shape (25,)

3. create an array of numbers from 1 to 25 with shape (5,5)

4.  create an array of 20 random integers ranging from 10 to 40 with shape (3,4)

5.  reshapse item (4) to be (4,5)

6.  give 2 examples of reshape






In [1]:
import numpy as np

In [46]:
#1 (difficult) create a 4 x 4 array, how can you print elements along the diagonal. write a for-loop
arr0 = np.arange(1, 17).reshape(4,4)

print(arr0)

for i in range(arr0.shape[0]):
    print(arr0[i, i])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
1
6
11
16


In [11]:
#2 easy. create an array of numbers from 1 to 25 with shape (25,)
arr = np.arange(1, 26)
arr, arr.shape, arr.ndim

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25]),
 (25,),
 1)

In [15]:
#3 create an array of numbers from 1 to 25 with shape (5,5)
arr2 = np.arange(1, 26).reshape(5,5)
arr2, arr2.shape, arr2.ndim

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 (5, 5),
 2)

In [18]:
#4 create an array of 20 random integers ranging from 10 to 40 with shape (3,4)
arr3 = np.random.randint(10, 40, 12).reshape(3,4)
arr3, arr3.shape, arr3.ndim

(array([[37, 21, 19, 17],
        [10, 25, 12, 19],
        [39, 23, 37, 10]]),
 (3, 4),
 2)

In [30]:
# 5 reshapse item (4) to be (4,5)
arr4 = np.random.randint(10, 40, 20).reshape(4,5)
arr4, arr4.shape, arr4.ndim

(array([[28, 28, 13, 20, 11],
        [18, 37, 13, 13, 22],
        [28, 16, 13, 25, 38],
        [35, 36, 32, 20, 10]]),
 (4, 5),
 2)

In [32]:
# 6. give 2 examples of reshape
# example1
arr5 = np.random.randint(1, 1000, 500).reshape(20,25)
arr5, arr5.shape, arr5.ndim

(array([[857, 233, 125, 800, 209, 273, 391,  64, 845, 772, 221, 499, 614,
         340, 615,   3, 734, 526, 889, 954, 958, 451, 314, 418, 184],
        [357, 413, 405,  91, 687, 238, 726, 873, 615, 618, 700, 474, 590,
         436, 148, 367, 524, 264, 973, 952, 246, 521, 263, 144, 666],
        [274, 773, 850,  59, 254, 651, 896, 674, 697, 187, 108, 562, 280,
         232, 132, 879, 986, 830,  80, 626, 517, 579, 976, 995, 871],
        [ 14, 437, 880, 618, 220, 190, 870, 630, 530, 700, 914, 222, 415,
         422, 806, 206, 639, 997, 200, 821, 599, 261, 785, 291, 898],
        [700, 152, 718, 663, 782, 933, 894, 189, 289, 623, 665, 756, 179,
          15, 596, 240, 887, 841, 859, 913, 803, 682, 760, 216, 100],
        [650, 980, 932, 551, 339, 757, 617, 715, 853, 243, 119, 437,  26,
         611, 299, 299, 234, 520, 244, 595,  31, 841, 572, 307, 838],
        [833, 724, 417, 226, 916, 293, 712,   6, 724, 752, 999, 526, 877,
          59,  74, 557, 287, 306, 588,  58, 919, 450, 604, 267

In [41]:
# 6. give 2 examples of reshape
# example2
arr6 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])
arr7 = arr6.reshape(-1)
arr7


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])